# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  database_data:
    driver: local

services:
  caddy:
    image: abiosoft/caddy:php
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
    links:
      - php
    volumes_from:
      - php
    restart: always
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
    environment:
      - JWT_SECRET=ThereIsNoAngelAboveButInOurHeart
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      # - database_data:/var/lib/mysql
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/seed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=qi1234
      - MYSQL_DATABASE=qidb
      - MYSQL_USER=qi
      - MYSQL_PASSWORD=qi1234