# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
    environment:
      - JWT_SECRET=ThereIsNoAngelAboveButInOurHeart
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      # - database_data:/var/lib/mysql
      - ./docker/mariadb:/opt/data
    command: --init-file /opt/data/seed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=qi1234
      - MYSQL_DATABASE=qidb
      - MYSQL_USER=qi
      - MYSQL_PASSWORD=qi1234