# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  database_data:
    driver: local

services:
  caddy:
    image: abiosoft/caddy:0.11.1-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/cert:/etc/caddycerts
      - ./docker/caddy/html/dist/qi-client:/var/www/html
    volumes_from:
      - php
    links:
      - php
    restart: always
    environment:
      - CADDYPATH=/etc/caddycerts
  php:
    build: ./docker/php/
    expose:
      - 9000
    # ports:
    #   - "8080:80"
    volumes:
      - ./docker/php/html:/var/www/php
    links:
      - mysql
    environment:
      - JWT_SECRET=ThereIsNoAngelAboveButInOurHeart
      - UPLOAD_PATH=/var/www/html/upload
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=qi1234
      - MYSQL_DATABASE=qidb
      - MYSQL_USER=qi
      - MYSQL_PASSWORD=qi1234
